;info codes:
.equ avr_was_reset = 200
.equ empty_bootloader_command_received = 201

.equ pf_tr_grant_permission = 203
.equ pf_tr_page_written = 204
.equ pf_tr_page_erased = 205
.equ pf_tr_resetting = 206

.equ PS_I2CNEXT = 207

;error codes:
.equ bl_rc_unknown_set_code = 100
.equ bl_first_page_empty = 101

.equ pf_tr_unknown_set_code = 102
.equ pf_tr_buffer_overflow_error = 103
.equ segment_count_error = 104
.equ seg_turn_val_error_code = 105

;graph codes
.equ graph_gyrzhDis_code = 10
.equ graph_speedDis_code = 11
.equ graph_full_time = 13
.equ graph_next_lap_code = 14
