;.include "src/mread/test/mread_test.asm"
;.include "src/i2c/gyr/tests/graph.asm"
;.include "src/physs/tests/physs_test.asm"
;.include "src/lapt/test/int1.asm"
;.include "src/bl/tests/bl_empty.asm"
;.include "src/bt/tests/echo_sync.asm"
.include "src/attempts/mapping.asm"
